### PR TITLE
add clustering (ported from Xamarin.Forms.GoogleMaps.Clustering)

### PR DESCRIPTION
**Pull request by sferhah**

### CODE REVIEW

**Comment by Alex-Dobrynin** [comment]
I suppose this need to be done as separate project in the solution and then for this project will be created separate nuget. you made a lot of changes and they should not affect original library.

Also, count that this library supports bindings out of the box now within MvvmMap control and MvvmMapHandlers and thus clustering also has to be integrated there

**Comment by sferhah** [comment]
> I suppose this need to be done as separate project in the solution and then for this project will be created separate nuget. you made a lot of changes and they should not affect original library.
> 
> Also, count that this library supports bindings out of the box now within MvvmMap control and MvvmMapHandlers and thus clustering also has to be integrated there

@Alex-Dobrynin , While I have ported an existing Xamarin project, I cannot guarantee my ability to maintain a NuGet package independently. The .NET MAUI community, in general, lacks sufficient developers, and the clustering feature is highly requested by your users. Thus, I believe integrating it into your project would be beneficial. The bindings can be incorporated at a later stage.

However, if you prefer to keep this as a separate project, you will need to remove the restrictive 'internal' access modifiers that hinder proper subclassing.

**Comment by Alex-Dobrynin** [comment]
@sferhah no, I meant that it should be separate project in this repo, like one .sln solution keeps few projects, just add core project reference to your one.

And this is not my lib, @themronion owns it, and he should decide how it should be done, i just suggested

**Comment by sferhah** [comment]
@Alex-Dobrynin My bad, I misread your post.

**Comment by themronion** [comment]
@sferhah I agree with Alex, since this brings in additional dependency `Xamarin.Google.Maps.Utils`, and most of the guys out there don't really need clustering it makes sense to leave it in a separate project. Don't worry about the nuget, I'll maintain it

**Comment by andersonvieiragomeslopes** [comment]
> @sferhah I agree with Alex, since this brings in additional dependency `Xamarin.Google.Maps.Utils`, and most of the guys out there don't really need clustering it makes sense to leave it in a separate project. Don't worry about the nuget, I'll maintain it

Hello Guys. @themronion @Alex-Dobrynin 

I hope I'm not late. I also agree, but now I stopped to look at the PR and do something separate and I came across a series of problems with classes that were changed to internal, a solution perhaps with isClustering= true/false might be the best solution to resolve this impasse, the PR has been ready for days and has not advanced, I want to help, so I proposed to look at the effort in the separation, it seems better to leave it together with the main project although I agree that the ideal would be the separation, if I can put a flag solve the problem that was mentioned?

**Comment by themronion** [comment]
@andersonvieiragomeslopes so, we close this one, i merge your pr and you will keep maintaining the cluster nuget. Did I understand everything correct?

**Comment by andersonvieiragomeslopes** [comment]
> @andersonvieiragomeslopes so, we close this one, i merge your pr and you will keep maintaining the cluster nuget. Did I understand everything correct?

That's not what I meant, but it could be, I'll take over this item now, I'll leave references to the code in the original repository and to the @sferhah  who did the initial work on this PR, I really need this item urgently and I'll take care of keeping it working.

You merge my PR, I'll keep everything related to the cluster, but you generate the nuget package, what do you think?

You can close this PR, I did the implementation in a new separate project, it was difficult, but it's ready.

**Comment by themronion** [comment]
Closing in favor of #57

**Pull request closed without merging**
