### PR TITLE
Clustering support for android and iOS

### PR DESCRIPTION
**Pull request by andersonvieiragomeslopes**
I'm bringing Xamarin.Forms.GoogleMaps.Clustering back to life and this adjustment is necessary, before this base class was public, but I noticed that there was a change, maybe that's why @sferhah implemented it within the project and not separately.

### CODE REVIEW

**Comment by Alex-Dobrynin** [comment]
I would add `public` and `protected virtual` to all classes and methods where is possible, also change private fields to protected properties where is possible, so it became as much flexible as possible

**Comment by andersonvieiragomeslopes** [comment]
> I would add `public` and `protected virtual` to all classes and methods where is possible, also change private fields to protected properties where is possible, so it became as much flexible as possible

I thought about doing this, but I noticed a necessary ripple effect in other places.

**Comment by andersonvieiragomeslopes** [comment]
Hi @themronion @Alex-Dobrynin 

I'm having build issues on my Mac, I won't be able to test iOS for now, can you validate if everything is ok there? The project has no compilation errors for iOS, everything should be working.


Then I intend to think of a way to integrate this with your mvvm implementation @Alex-Dobrynin

#44  #47

**Comment by themronion** [comment]
Clustering support is in this package: https://www.nuget.org/packages/Onion.Maui.GoogleMaps.Clustering

**Pull request merged**
